### ISSUE TITLE
403 error is shown instead of setting the state

### ISSUE THREAD

**Issue by pirog-anna** [e-moe/levi9voter#28]
Steps to reproduce:
1. Login as admin
2. Open some article with "Voting in progress" status
3. Choose in State drop down some valid value
4. Press "Change state" button
Actual result:403 error - Access Denied is shown
Expected result: Status is changed

**Comment by holyspecter** [comment]
@pirog-anna article with "Voting in progress" status can not be edited (see #3 for details). Though 403 is an expected response in this case we still need to hide edit button.

**Comment by alexandr-kalenyuk** [comment]
@holyspecter just open Post with state "Voting in progress" you will see Change State form which works incorrectly. Edit button is hidden.

**Comment by Ishugaev** [comment]
looks like already fixed

**Comment by Ishugaev** [comment]
problem in line 204, $this->denyAccessUnlessGranted(PostVoter::EDIT, $post);

It needs to investigate why function denyAccessUnlessGranted works incorrect in this case
