### ISSUE TITLE
Votes workflow

### ISSUE THREAD

**Issue by e-moe** [e-moe/levi9voter#3]
Draft - visible only to author, can be edited only by author
Review - visible by author and by admin, only admin can edit and publish
Published - visible by all, not editable, can be voted (+1 / -1)
Approved - visible by all, not editable, voting closed
Declined - visible by all, not editable, voting closed

**Comment by Ishugaev** [comment]
Drafts and filter by drafts  also should be removed from votes list, author can see/edit draft only in admin part.

By default user should go to votes list page.
