### ISSUE TITLE
500 internal server error by removing the image

### ISSUE THREAD

**Issue by pirog-anna** [e-moe/levi9voter#80]
Steps to reproduce:
1. Open vote creation page
2. Fill all fields with valid data
3. Add image by clicking "Upload image" button
4. Press "Remove" button
Actual result: Image isn't removed. 500 error is shown in the console
Expected result: Uploaded image is deleted

**Comment by stanislav-sulima** [comment]
I guess this issue was related with opcache. Please, recheck it.
