### ISSUE TITLE
wrong email list after approving

### ISSUE THREAD

**Issue by pirog-anna** [e-moe/levi9voter#82]
Steps to reproduce:
1. Add some post and publish it
2. Some people should comment it
3. Approve the post
Actual result: The email is sent to creator of post and all people who put the comment
Expected result: The email is sent to creator only (for admin possible as well)

**Comment by stanislav-sulima** [comment]
This functionality has been implemented according to https://github.com/e-moe/levi9voter/issues/5
This is not a bug.
